name: VickiJ
favicon: null
layout_spectrum: 0.48806
typography_spectrum: 0.8258812427520752
title: Building Industry Empires
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a0c'
    - '#71463e'
    - '#a79789'
    - '#9b0b1d'
    - '#3e7b9d'
  brandStrength: 0.25
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
