name: VickiJ
favicon: null
layout_spectrum: 0.7063049105927348
typography_spectrum: 0.8258812427520752
title: Building Industry Empires
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.5708969570696354
  lightness: 0.41599045414477587
  saturation: 0.3685487855691463
  rhythmicContrast: 0.9903930255677551
purpose: []
